# SonarQube Configuration for Frontend (React.js)

# URL of your SonarQube server
sonar.host.url=http://192.168.33.10:9000  

# your-frontend-project-key
sonar.projectKey=recruitpro-frontend  

sonar.projectName=Frontend
sonar.projectVersion=1.0.0

# Path to the source code
sonar.sources=src

# Path to the test code
#sonar.tests=src

# Exclude node_modules
sonar.exclusions=node_modules/**

# Encoding
sonar.sourceEncoding=UTF-8

# Sonar token for authentication
sonar.login=squ_391fc82deb8ea0e5b10ed2c4dc0226ad7e235c05
