# must be unique in your SonarQube instance
sonar.projectKey=recruitpro-ats-system

# URL of your SonarQube server
sonar.host.url=http://192.168.33.10:9000  

# project metadata
sonar.projectName=ATS-Module
sonar.projectVersion=1.0

# Path to source code
sonar.sources=.

# Encoding
sonar.sourceEncoding=UTF-8

# Language
sonar.language=py

# Optional: Exclude pickle files, templates, etc.
sonar.exclusions=**/*.pkl,**/templates/**,**/__pycache__/**

# Optional: Path to tests if you have any
# sonar.tests=tests


# Sonar token for authentication
sonar.login=squ_391fc82deb8ea0e5b10ed2c4dc0226ad7e235c05